# Generated by Django 4.0.2 on 2022-02-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['picture'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-start'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(max_length=250, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(verbose_name='Трудоёмкость'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hard',
            field=models.BooleanField(verbose_name='Жёсткая'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.BooleanField(verbose_name='Важная'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(verbose_name='Прогресс выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_mode',
            field=models.IntegerField(verbose_name='Режим повторения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=250, verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.attachment', verbose_name='Вложение'),
        ),
    ]
