# Generated by Django 4.0.2 on 2022-02-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.attachment', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Трудоёмкость'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.label', verbose_name='Метка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прогресс выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_mode',
            field=models.IntegerField(blank=True, choices=[(None, 'Выберите режим повтора'), (0, 'Без повтора'), (1, 'Ежедневно'), (2, 'Еженедельно'), (3, 'Ежемесячно')], default=0, null=True, verbose_name='Режим повторения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
